services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: lebenshilfe
      MYSQL_DATABASE: lebenshilfe_dev
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
