services:
  app:
    image: localhost:5000/lebenshilfe:latest
    labels:
      alloy-logging: true
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - .env
    environment:
      - LOG_PRETTY=false
